"""One-shot generator for implementation/issues audit tickets."""
from __future__ import annotations

import pathlib

TICKETS = [
    ("ISS-001", "build", "high", "frozen-sandbox-spawns-gui-exe",
     "Sandbox uses sys.executable -m when frozen; GUI exe respawns instead of worker.",
     "engine/sandbox/runner.py; packaging/launcher_gui.py",
     "Add --sandbox-worker argv dispatch in launcher; spawn exe with flag when frozen."),
    ("ISS-002", "build", "high", "writable-root-appdata",
     "Results/settings write next to exe; fails under Program Files.",
     "engine/paths.py; engine/core/config_io.py",
     "Use LOCALAPPDATA/CodeScenarios; seed configs on first run."),
    ("ISS-003", "build", "med", "resource-root-meipass",
     "resource_root ignores sys._MEIPASS; __file__ asset loads fragile.",
     "engine/paths.py; ui/render/*.py",
     "Use _MEIPASS when frozen; route assets through resource_path()."),
    ("ISS-004", "build", "med", "ruff-bundling-silent-fail",
     "Ruff missing in dist returns empty violations silently.",
     "packaging/code_scenarios.spec; engine/analysis/static.py",
     "Assert ruff.exe in build; surface missing tool in metrics."),
    ("ISS-005", "build", "med", "enable-ai-default",
     "Shipped default.toml has enable_ai=true vs code False.",
     "configs/default.toml; ui/screens/settings.py",
     "Ship false; add Settings toggle."),
    ("ISS-010", "ui", "high", "layout-in-draw-ghost-clicks",
     "Button rects updated in draw() but events run first.",
     "ui/screens/*.py", "Layout in on_enter and before handle_event."),
    ("ISS-011", "ui", "high", "menu-hardcoded-1024x800",
     "Menu geometry assumes fixed 1024x800.", "ui/screens/menu.py",
     "Derive from surface.get_width/height()."),
    ("ISS-012", "ui", "med", "cursor-never-resets",
     "Hand cursor sticks after hover.", "ui/widgets/controls.py; ui/screens/menu.py",
     "Central cursor reset each frame."),
    ("ISS-013", "ui", "med", "coach-quest-click-clip",
     "Quest card hits ignore viewport clip.", "ui/screens/coach.py",
     "Require collidepoint with quests panel rect."),
    ("ISS-014", "ui", "med", "button-mouseup-without-press",
     "Button/ListRow activate on release without press tracking.",
     "ui/widgets/controls.py", "Track press-in-rect before click."),
    ("ISS-015", "ui", "med", "misleading-enabled-buttons",
     "Open Folder enabled with no session; Browse/Folder same icon.",
     "ui/screens/scores.py; ui/screens/menu.py",
     "Disable when no session; distinct icons."),
    ("ISS-016", "ui", "med", "uk-label-truncation",
     "Fixed button widths clip Ukrainian labels.", "ui/screens/*; ui/theme.py",
     "Locale-aware min widths from label metrics."),
    ("ISS-017", "ui", "low", "coach-tabs-overflow",
     "Many player tabs run off-screen.", "ui/screens/coach.py",
     "Horizontal scroll or wrap for tabs."),
    ("ISS-020", "style", "med", "scrollbar-drift",
     "Four different scrollbar implementations.", "ui/skin/chrome.py; ui/screens/scores.py",
     "Unify on skin.draw_scrollbar."),
    ("ISS-021", "style", "med", "selectable-card-drift",
     "Cards hand-rolled across menu/ListRow/coach.",
     "ui/screens/menu.py; ui/widgets/controls.py", "Shared selectable card helper."),
    ("ISS-022", "style", "low", "hardcoded-english-ui-strings",
     "English strings bypass i18n in scores/settings/ollama.",
     "ui/screens/scores.py; settings.py", "Move to ui_strings/feedback i18n."),
    ("ISS-030", "logic", "high", "boss-difficulty-not-in-replay",
     "boss_difficulty not stored/restored in replay.",
     "engine/core/session.py; engine/core/replay.py",
     "Persist in replay.json; restore on ReplaySession."),
    ("ISS-031", "logic", "high", "boss-acts-after-death",
     "Boss still attacks after HP hits 0 same turn.", "scenarios/boss_fight/game.py",
     "Skip boss turn when boss_hp<=0 before attacks."),
    ("ISS-032", "logic", "high", "sandbox-denylist-gaps",
     "__import__/eval/exec not blocked at load.", "engine/core/loader.py",
     "AST checks for Call nodes; unify denylist with config."),
    ("ISS-033", "logic", "high", "lexicographic-turn-order",
     "opponent acts before student; p10 before p2.",
     "scenarios/*/game.py; engine/core/loader.py",
     "Use setup order with zero-padded ids."),
    ("ISS-034", "logic", "med", "scoring-weights-unvalidated",
     "Weights not validated; scoring ignores user scenario.toml when frozen.",
     "engine/scoring/weights.py", "Validate sum==1; use scenario_toml_read_path."),
    ("ISS-035", "logic", "med", "mana-pools-energy-edge-cases",
     "Discounted attack with 1-2 energy; gather at max counted.",
     "scenarios/mana_pools/game.py",
     "Require full attack_cost; skip gather increment at max."),
    ("ISS-036", "logic", "med", "boss-fight-config-dead-code",
     "multi_target dead; diff-1 not random; docstring/size mismatch.",
     "scenarios/boss_fight/; ui i18n", "Honor config; random target; fix docs/UI HP."),
    ("ISS-037", "logic", "med", "boss-scoring-rounding-metrics",
     "Damage share rounding; boss_metrics not in metrics.json.",
     "scenarios/boss_fight/game.py; engine/core/live_game.py",
     "Fix rounding; wire boss_metrics."),
    ("ISS-038", "logic", "med", "sandbox-worker-no-restart",
     "Worker killed on timeout never restarted; timeout no CQ cap.",
     "engine/sandbox/runner.py; engine/scoring/combined.py",
     "Restart worker on timeout; cap CQ on timeouts too."),
    ("ISS-039", "logic", "med", "mana-relative-scoring-stall",
     "Relative scores inflate gameplay; false stall feedback.",
     "scenarios/mana_pools/game.py; engine/analysis/movement.py",
     "Absolute threshold scoring; skip stall on relative scores."),
    ("ISS-040", "logic", "low", "resource-wars-edge-cases",
     "Silent ignore of wrong actions; placement undercount; ties.",
     "scenarios/resource_wars/game.py",
     "Emit events; retry placement; document ties."),
    ("ISS-050", "feedback", "high", "bot-source-not-snapshotted",
     "Coach reads live bot path; breaks if file moved.",
     "engine/core/session.py; ui/coach_data.py",
     "Copy bots/{id}.py into session; update bot_files."),
    ("ISS-051", "feedback", "high", "teacher-export-missing",
     "No CSV/JSON export for classroom grading.", "ui/screens/scores.py",
     "Export button writes session summary CSV/JSON."),
    ("ISS-052", "feedback", "med", "scores-coach-wrong-player",
     "Scores->Coach ignores clicked row player_id.",
     "ui/screens/scores.py; ui/app.py", "Pass player_id to goto_coach."),
    ("ISS-053", "feedback", "med", "ai-reports-english-only",
     "AI report generation hardcodes lang=en.",
     "ai/prompts.py; engine/analysis/ai_report.py", "Pass config locale to prompts."),
    ("ISS-054", "feedback", "med", "feedback-lines-severity",
     "Many cards lack line anchors; severity not shown.",
     "engine/analysis/feedback.py; ui/render/quest_card.py",
     "Add lines where possible; show severity chip."),
    ("ISS-055", "feedback", "low", "feedback-heuristic-mismatch",
     "Threshold mismatches and false-positive heuristics.",
     "engine/analysis/static.py; feedback.py",
     "Align thresholds; scenario-aware heuristics."),
    ("ISS-060", "config", "med", "dead-duplicated-knobs",
     "max_turns unused; timeout defaults differ; duplicate denylists.",
     "configs/default.toml; engine/core/config.py",
     "Single source; wire or remove dead keys."),
    ("ISS-061", "config", "med", "config-consolidation",
     "Multiple scenario.toml readers; Settings incomplete.",
     "engine/core/config_io.py; ui/screens/settings.py",
     "Single facade; enable_ai/volume in Settings."),
]

def main() -> None:
    root = pathlib.Path(__file__).resolve().parent.parent / "implementation" / "issues"
    root.mkdir(parents=True, exist_ok=True)
    for tid, area, sev, slug, symptom, files, fix in TICKETS:
        title = slug.replace("-", " ").title()
        path = root / f"{tid}-{slug}.md"
        path.write_text(
            f"---\nid: {tid}\narea: {area}\nseverity: {sev}\nstatus: open\n---\n\n"
            f"# {tid}: {title}\n\n## Symptom\n{symptom}\n\n"
            f"## Affected files\n{files}\n\n## Fix sketch\n{fix}\n",
            encoding="utf-8",
        )
    print(f"Wrote {len(TICKETS)} tickets to {root}")

if __name__ == "__main__":
    main()
